#pragma once

#define ERR_MAX_ENTITY "FAIL - ALLOC ENTITY : MAXIMUM NUMBER OF ENTITY\n"
#define ERR_FREE_ENTITY "FAIL - FREE ENTITY : NOT ALLOCATED ENTITY\n"

#define ERR_MAX_COMPONENT "FAIL - REGISTER ERR_MAX_COMPONENT : MAXIMUM NUMBER OF ERR_MAX_COMPONENT\n"